### ISSUE TITLE
Each game should use single currency

### ISSUE THREAD

**Issue by tvvf** [OfflinePoker/Tournament#19]
Cash games as well as Tournaments should have a defined currency, removing the need to enter the currency for (almost) any action.

**Comment by tvvf** [comment]
Hmm, strange. I thought I had seen that issue, but now have a hard time reproducing.

**Comment by OfflinePoker** [comment]
The creation pages for cash game and tournament contain an initial Buy-In amount. This amount contains the currency. Afterwards all entered amounts are without currency.
